# -- Markup --
# These settings are required for the theme to function.

[goldmark]
  [goldmark.renderer]
    unsafe = true
    hardWraps = true

  [goldmark.extensions]
    [goldmark.extensions.passthrough]
      enable = true
      [goldmark.extensions.passthrough.delimiters]
        block = [['\[', '\]'], ['$$', '$$']]
        inline = [['\(', '\)']]


[highlight]
  noClasses = false
  codeFences = true
  guessSyntax = true
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  font_size = 19
  lineNumbersInTable = true
  tabWidth = 4
  style = "murphy"

[tableOfContents]
  startLevel = 2
  endLevel = 4


[params.gitalk]
owner = "Yuoek"
repo = "comment"
clientId = "Ov23li4DmR0SAirPyvSz"
clientSecret = "b8132e8e29d151157ec9ce261d64c5e89da9fe9c"
