# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
 name = "せいかつ"
 weight = 20

[[main]]
 name = "せいかつ :)"
 parent = "せいかつ"
 pageRef = "life"
 weight = 21

[[main]]
 name = "学習"
 parent = "せいかつ"
 pageRef = "life/study"
 weight = 22


[[main]]
 name = "運動"
 parent = "せいかつ"
 pageRef = "life/sport"
 weight = 23

[[main]]
 name = "マイナー言語"
 parent = "せいかつ"
 pageRef = "life/language"
 weight = 24

[[main]]
 name = "芸術"
 weight = 30

[[main]]
 name = "芸術 :)"
 parent = "芸術"
 pageRef = "art"
 weight = 31

[[main]]
 name = "文学"
 parent = "芸術"
 pageRef = "art/literature"
 weight = 32

[[main]]
 name = "絵画"
 parent = "芸術"
 pageRef = "art/painting"
 weight = 33

[[main]]
 name = "音楽"
 parent = "芸術"
 pageRef = "art/music"
 weight = 34
 
[[main]]
 name = "映画"
 parent = "芸術"
 pageRef = "art/film"
 weight = 35

[[main]]
 name = "かがく"
 weight = 40

[[main]]
 name = "かがく :)"
 parent = "かがく"
 pageRef = "science"
 weight = 41

[[main]]
 name = "コンピューター"
 parent = "かがく"
 pageRef = "science/computer"
 weight = 42

[[main]]
 name = "すうがく"
 parent = "かがく"
 pageRef = "science/mathematics"
 weight = 43

[[main]]
 name = "物理"
 parent = "かがく"
 pageRef = "science/physics"
 weight = 44

[[main]]
 name = "てんもん"
 parent = "かがく"
 pageRef = "science/astronomy"
 weight = 45

[[main]]
 name = "残り"
 weight = 50

[[main]]
 name = "残り :)"
 parent = "残り"
 pageRef = "other"
 weight = 51

[[main]]
 name = "ちり"
 parent = "残り"
 pageRef = "other/geography"
 weight = 52

[[main]]
 name = "歴史"
 parent = "残り"
 pageRef = "other/history"
 weight = 53

[[main]]
 name = "せいかつ0123"
 weight = 80

[[main]]
 name = "せいかつ | 0123"
 parent = "せいかつ0123"
 pageRef = "life0123"
 weight = 81

[[main]]
 name = "せいかつ | 0"
 parent = "せいかつ0123"
 pageRef = "life0123/life0"
 weight = 82

[[main]]
 name = "芸術 | 1"
 parent = "せいかつ0123"
 pageRef = "life0123/art1"
 weight = 83

[[main]]
 name = "かがく | 2"
 parent = "せいかつ0123"
 pageRef = "life0123/science2"
 weight = 84

[[main]]
 name = "残り | 3"
 parent = "せいかつ0123"
 pageRef = "life0123/other3"
 weight = 85

[[subnavigation]]
 name = "一言一行"
 pageRef = "day/dayQuote"
 weight = 91

[[subnavigation]]
 name = "詩歌美文"
 pageRef = "day/dayPoetry"
 weight = 92

[[subnavigation]]
 name = "審美絵画"
 pageRef = "day/dayPaint"
 weight = 93

[[subnavigation]]
 name = "音の楽章"
 pageRef = "day/dayMusic"
 weight = 94

[[subnavigation]]
 name = "光影視聴"
 pageRef = "day/dayFilm"
 weight = 95


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
 name = "アーカイブ"
 pageRef = "archives"
 weight = 10

[[footer]]
  name = "タグ"
  pageRef = "tags"
  weight = 11

[[footer]]
  name = "分類"
  pageRef = "categories"
  weight = 12


