# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
 name = "Life"
 weight = 20

[[main]]
 name = "Life :)"
 parent = "Life"
 pageRef = "life"
 weight = 21

[[main]]
 name = "Study"
 parent = "Life"
 pageRef = "life/study"
 weight = 22


[[main]]
 name = "Sport"
 parent = "Life"
 pageRef = "life/sport"
 weight = 23

[[main]]
 name = "Language"
 parent = "Life"
 pageRef = "life/language"
 weight = 24

[[main]]
 name = "Art"
 weight = 30

[[main]]
 name = "Art :)"
 parent = "Art"
 pageRef = "art"
 weight = 31

[[main]]
 name = "Literature"
 parent = "Art"
 pageRef = "art/literature"
 weight = 32

[[main]]
 name = "Painting"
 parent = "Art"
 pageRef = "art/painting"
 weight = 33

[[main]]
 name = "Music"
 parent = "Art"
 pageRef = "art/music"
 weight = 34
 
[[main]]
 name = "Film"
 parent = "Art"
 pageRef = "art/film"
 weight = 35

[[main]]
 name = "Science"
 weight = 40

[[main]]
 name = "Science :)"
 parent = "Science"
 pageRef = "science"
 weight = 41

[[main]]
 name = "Computer"
 parent = "Science"
 pageRef = "science/computer"
 weight = 42

[[main]]
 name = "Mathematics"
 parent = "Science"
 pageRef = "science/mathematics"
 weight = 43

[[main]]
 name = "Physics"
 parent = "Science"
 pageRef = "science/physics"
 weight = 44

[[main]]
 name = "Astronomy"
 parent = "Science"
 pageRef = "science/astronomy"
 weight = 45

[[main]]
 name = "Other"
 weight = 50

[[main]]
 name = "Other :)"
 parent = "Other"
 pageRef = "other"
 weight = 51

[[main]]
 name = "Geography"
 parent = "Other"
 pageRef = "other/geography"
 weight = 52

[[main]]
 name = "History"
 parent = "Other"
 pageRef = "other/history"
 weight = 53

[[main]]
 name = "Life0123"
 weight = 80

[[main]]
 name = "Life | 0123"
 parent = "Life0123"
 pageRef = "life0123"
 weight = 81

[[main]]
 name = "Life | 0"
 parent = "Life0123"
 pageRef = "life0123/life_0"
 weight = 82

[[main]]
 name = "Art | 1"
 parent = "Life0123"
 pageRef = "life0123/art_1"
 weight = 83

[[main]]
 name = "Science | 2"
 parent = "Life0123"
 pageRef = "life0123/science_2"
 weight = 84

[[main]]
 name = "Other | 3"
 parent = "Life0123"
 pageRef = "life0123/other_3"
 weight = 85

[[subnavigation]]
 name = "quote"
 pageRef = "day/dayQuote"
 weight = 91

[[subnavigation]]
 name = "poetry"
 pageRef = "day/dayPoetry"
 weight = 92

[[subnavigation]]
 name = "paint"
 pageRef = "day/dayPaint"
 weight = 93

[[subnavigation]]
 name = "music"
 pageRef = "day/dayMusic"
 weight = 94

[[subnavigation]]
 name = "film"
 pageRef = "day/dayFilm"
 weight = 95

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
 name = "Archives"
 pageRef = "archives"
 weight = 10

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 11

[[footer]]
  name = "Categories"
  pageRef = "categories"
  weight = 12


